export const APP_ROUTES = {
    home: "/",
    search: "/noi-luu-tru",
    login: "/dang-nhap",
    register: "/dang-ky",
    forgotPassword: "/quen-mat-khau",
    hostLanding: "/tro-thanh-host",
    hostRegister: "/tro-thanh-host/dang-ky",
    hostStatus: "/tro-thanh-host/trang-thai",
    accountProfile: "/account/profile",
    accountTrips: "/account/trips",
    ownerDashboard: "/chu-nha/cho-nghi",
    hostOverviewLegacy: "/chu-nha/tong-quan",
    hostProperties: "/chu-nha/cho-nghi",
    hostNewProperty: "/chu-nha/cho-nghi/them-moi",
    hostBookings: "/chu-nha/dat-phong",
    hostCalendar: "/chu-nha/lich-luu-tru",
    hostGuests: "/chu-nha/khach-luu-tru",
    hostPayments: "/chu-nha/thanh-toan",
    hostReviews: "/chu-nha/danh-gia",
    hostReports: "/chu-nha/bao-cao",
    hostSupport: "/chu-nha/ho-tro",
    hostSettings: "/chu-nha/cai-dat",
    adminOverview: "/admin",
    adminUsers: "/admin/nguoi-dung",
    adminModeration: "/admin/kiem-duyet",
    adminRoles: "/admin/phan-quyen",
    guestPayment: "/thanh-toan/:bookingId",
    guestPaymentDetail: (bookingId: string) => `/thanh-toan/${bookingId}`,
    villaDetail: (villaId: string) => `/villa/${villaId}`,
} as const;
